### ISSUE TITLE
Questions regarding HLA genotype in data

### ISSUE THREAD

**Issue by YuhaoTan2** [immunogenomics/cdr3-QTL#1]
Hi, 

Thanks for providing the code!

I am trying to reproduce some results in the manuscript, but encounter a question about the HLA genotype. The identifiers in data/genotype/HLA_*.matrix start with "HIP", but the identifiers in the TCR dataset downloaded from https://clients.adaptivebiotech.com/pub/emerson-2017-natgen start with "P". How do I map between the "HIP" identifier and "P" identifier? Or are there any other sources that I could download the HLA genotype with identifiers starting with "P"?

Thank you for your help in advance! I am looking forward to your reply.

**Comment by ameyers99** [comment]
Hi, 
Just following up on this to see if there was a resolution? 
Thank you for your time.

**Comment by YuhaoTan2** [comment]
Hi,

If you have an old version of the Emerson dataset, you can manually match the HIP and P identifier by comparing TCR sequences.

**Comment by ameyers99** [comment]
Hi, 
Thank you for your quick reply. Do you have a file that maps HIP and P identifiers that you are willing to share? 
Best
